# https://alacritty.org/config-alacritty.html

[window]
decorations = "None"  # Default: "Full"
opacity = 0.85  # Default: 1.0
startup_mode = "Fullscreen"  # Default: "Windowed"

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "ExtraLight" }  # Default for Linux/BSD: "monospace", Regular
bold = { family = "JetBrainsMonoNL Nerd Font", style = "Medium" }  # Inherits family from normal, Default style: Bold
italic = { family = "JetBrainsMonoNL Nerd Font", style = "Medium Italic" }  # Inherits family from normal, Default style: Italic
bold_italic = { family = "JetBrainsMonoNL Nerd Font", style = "Bold Italic" }  # Inherits family from normal, Default style: Bold Italic
size = 7.5  # Default: 11.25

[terminal]
# Controls the OSC 52 behavior for clipboard interactions
osc52 = "CopyPaste"  # Default: "OnlyCopy"

[mouse]
hide_when_typing = true  # Default: false
